version: "3.8"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=openflights
    volumes:
      - ./app_data/postgres:/var/lib/postgresql/data/
      - ./data/routes.sql:/docker-entrypoint-initdb.d/routes.sql
      - ./data/routes-treated.csv:/routes-treated.csv
      - ./data/airlines.sql:/docker-entrypoint-initdb.d/airlines.sql
      - ./data/airlines.csv:/airlines.csv
      - ./data/airports.sql:/docker-entrypoint-initdb.d/airports.sql
      - ./data/airports.csv:/airports.csv
      - ./data/planes.sql:/docker-entrypoint-initdb.d/planes.sql
      - ./data/planes.csv:/planes.csv

volumes:
  postgres_data:
  app_data:
