version: "3.8"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=openflights
    volumes:
      - ./app_data/postgres:/var/lib/postgresql/data/
      - ./routes.sql:/docker-entrypoint-initdb.d/routes.sql

volumes:
  postgres_data:
  app_data:
