version: "3.8"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=openflights
    volumes:
      - ./app_data/postgres:/var/lib/postgresql/data/
      - ./data/1-planes.sql:/docker-entrypoint-initdb.d/1-planes.sql
      - ./data/2-insert-planes.sql:/docker-entrypoint-initdb.d/2-insert-planes.sql
      - ./data/3-airlines.sql:/docker-entrypoint-initdb.d/3-airlines.sql
      - ./data/4-airports.sql:/docker-entrypoint-initdb.d/4-airports.sql
      - ./data/5-routes.sql:/docker-entrypoint-initdb.d/5-routes.sql
      - ./data/6-insert-routes.sql:/docker-entrypoint-initdb.d/6-insert-routes.sql
      - ./data/airlines.csv:/airlines.csv
      - ./data/airports.csv:/airports.csv

volumes:
  postgres_data:
  app_data:
